# Generated by Django 5.2.6 on 2025-09-09 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('prompt', 'prompt'), ('response', 'response')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_sha256', models.CharField(db_index=True, default='', max_length=64)),
                ('canonical_sha256', models.CharField(db_index=True, default='', max_length=64)),
                ('tokens_len', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
